### PR TITLE
Auto publish to PyPI

### PR DESCRIPTION
**Pull request by ocefpaf**
I modernized things a bit and publishing should be as easy as just issuing a tag.

@ericdill I don't have enough rights here to add the PyPI token. Can you do that?

### CODE REVIEW

**Comment by ericdill** [comment]
how / where do I need to add the pypi token?

**Comment by ocefpaf** [comment]
> how / where do I need to add the pypi token?

You can create one by clicking here

https://pypi.org/manage/account/token/

then you add it as a repository secret here

https://github.com/ericdill/depfinder/settings/secrets/actions/new

and we should be all set.

**Comment by ocefpaf** [comment]
I'm not sure who coverage works but this PR deletes more than it adds and the two places where code is added are the tests and a version scheme in setup.py, for both I cannot really add tests for to increase coverage :-/

**Comment by ocefpaf** [comment]
Closing this and re-working it in #79

**Pull request closed without merging**
