### PR TITLE
fix windows encoding

### PR DESCRIPTION
**Pull request by ocefpaf**
Ideally we should add some Windows tests.

Original bug report: https://gist.github.com/ocefpaf/b9107a26f8b60fca186bc9ec9d42011c

Ping @rsignell-usgs

### CODE REVIEW

**Comment by ericdill** [comment]
> Ideally we should add some Windows tests.

...ideally 😈

**Comment by ericdill** [comment]
@ocefpaf is it safe for me to assume that you know what you're doing with this utf-8 encoding?

**Comment by ocefpaf** [comment]
> @ocefpaf is it safe for me to assume that you know what you're doing with this utf-8 encoding? (...i don't, but I'm 100% happy to trust that you're doing the right thing here)

To be completely honest I'm not 100% sure :grimacing: According to my Google-StackOverflowFu that seems to be the recommended way to parse the notebook `json` on Windows and should be harmless on other platforms. (I never saw a notebooks that is not: `HTML document, UTF-8 Unicode text, with very long lines`.)

I'll try to add some Windows tests in the future but I cannot afford to do so right now. I need to move on to another project.

**Comment by ericdill** [comment]
Understood. No rush on windows tests. It's gone this long without them. No burning need to add them now :)

**Comment by ocefpaf** [comment]
Thanks @ericdill!

**Pull request merged**
