### PR TITLE
allow blacklist of files

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by ericdill** [comment]
Right now you can only provide one pattern for blacklisting. Do you have a use case that requires more than one blacklisting pattern?

**Comment by CJ-Wright** [comment]
Most likely. I'll put in the option to give a list.

**Comment by ocefpaf** [comment]
I was going to approach this problem like a "linter" where the files /patterns to skip would be provided in a ignore file. (Less typing and more copying when the ignore patters are the same across projects.)

**Comment by CJ-Wright** [comment]
Where would the ignore file live, in the project or  somewhere special on the user's machine?

We could do both, cli and file based.

**Comment by ocefpaf** [comment]
> Where would the ignore file live, in the project or somewhere special on the user's machine?

Something like a `depfinder.ini` at the root of the project.

> We could do both, cli and file based.

That would be awesome but don't let this idea delay you on this PR. It is good to go IMO.

**Comment by CJ-Wright** [comment]
I'd be a little wary of having config files in the projects themselves. Although they are nice and self contained, I worry about requiring buy in from developers which have never heard of depfinder. I guess one could write a script which put the `ini` file in temporally if one didn't exist.

Hmm, @ericdill would you be willing to put off multi-pattern matching for another PR?

**Comment by ericdill** [comment]
To be clear I'm not asking for multiple pattern blacklisting. I just wanted to ask if you had a use case for multiple pattern blacklisting 😀. Sorry for the confusion

**Pull request merged**
